[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pflsim"
version = "0.0.1"
requires-python = ">=3.9"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"

[tool.hatch.build.targets.wheel]
packages = ["src/pflsim"]